### ISSUE TITLE
npm instal weak not working on linux mint 17.1

### ISSUE THREAD

**Issue by sarasfox** [TooTallNate/node-weak#50]
```
> weak@0.4.1 install /home/gadget-girl/App/test/node_modules/jquerygo/node_modules/phantom/node_modules/dnode/node_modules/weak
> node-gyp rebuild

make: Entering directory `/home/gadget-girl/App/test/node_modules/jquerygo/node_modules/phantom/node_modules/dnode/node_modules/weak/build'
  CXX(target) Release/obj.target/weakref/src/weakref.o
make: g++: Command not found
make: *** [Release/obj.target/weakref/src/weakref.o] Error 127
make: Leaving directory `/home/gadget-girl/App/test/node_modules/jquerygo/node_modules/phantom/node_modules/dnode/node_modules/weak/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/gadget-girl/App/test/node_modules/jquerygo/node_modules/phantom/node_modules/dnode/node_modules/weak
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing weak@0.4.1
```

is the Error that i am get when try to install weak.

**Comment by wwcline** [comment]
I'm seeing a similar error on Mac OS 10.9.5, using io.js node version 1.2.0 and npm version 2.7.5:

```
$ npm install weak
/
> weak@0.4.1 install /Users/<REDACTED>/node_modules/weak
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at emitOne (events.js:80:20)
gyp ERR! stack     at Request.emit (events.js:150:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1139:10)
gyp ERR! stack     at emitOne (events.js:75:13)
gyp ERR! stack     at ClientRequest.emit (events.js:150:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:397:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:287:20)
gyp ERR! stack     at emitOne (events.js:75:13)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/<REDACTED>/node_modules/weak
gyp ERR! node -v v1.2.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "weak"
npm ERR! node v1.2.0
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE

npm ERR! weak@0.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the weak@0.4.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the weak package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls weak
npm ERR! There is likely additional logging output above.
```

**Comment by haydenbleasel** [comment]
Same on Ubuntu 14.04:

```
root:~/test/htmltopdf# npm install weak
-
> weak@0.4.1 install /root/test/htmltopdf/node_modules/weak
> node-gyp rebuild

make: Entering directory `/root/test/htmltopdf/node_modules/weak/build'
  CXX(target) Release/obj.target/weakref/src/weakref.o
make: g++: Command not found
make: *** [Release/obj.target/weakref/src/weakref.o] Error 127
make: Leaving directory `/root/test/htmltopdf/node_modules/weak/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-52-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/test/htmltopdf/node_modules/weak
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Linux 3.13.0-52-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "weak"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! weak@0.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the weak@0.4.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the weak package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls weak
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/test/htmltopdf/npm-debug.log
```

**Comment by haydenbleasel** [comment]
Whoops overlooked something in the error log. @sarasfox Install g++ with `sudo apt-get install g++`

**Comment by robcolburn** [comment]
I believe this is resolved in `weak` 1.x.  Please try again.

Some Notes:
* Be sure your npm >= 1.4
* On linux, be sure you have a current version of g++. `weak` depends on a module that wraps some native code bindings, so a successful `node-gyp` run is required to build correctly on your system.
https://github.com/TooTallNate/node-weak/blob/master/.travis.yml#L3

**Comment by wwcline** [comment]
I'm still seeing a problem, which looks like the same message I was getting before:

```
~/Documents/weak_test $ npm install weak@">=1.0"
\
> weak@1.0.0 install /Users/wwcline/Documents/weak_test/node_modules/weak
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at emitOne (events.js:80:20)
gyp ERR! stack     at Request.emit (events.js:150:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1139:10)
gyp ERR! stack     at emitOne (events.js:75:13)
gyp ERR! stack     at ClientRequest.emit (events.js:150:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:397:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:287:20)
gyp ERR! stack     at emitOne (events.js:75:13)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/wwcline/Documents/weak_test/node_modules/weak
gyp ERR! node -v v1.2.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "weak@>=1.0"
npm ERR! node v1.2.0
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE

npm ERR! weak@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the weak@1.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the weak package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls weak
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/clinew/Documents/weak_test/npm-debug.log
```

In case it helps, here's some info about my copy of `g++`:

```
~/Documents/weak_test $ which g++
/usr/bin/g++
~/Documents/weak_test $ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```

**Comment by TooTallNate** [comment]
Please update to node v4
